name: Bash Script Kontrolü (CI)

on:
  push:
    branches: [ "main" ] 

jobs:
  shellcheck:  
    runs-on: ubuntu-latest 

    steps:
      - name: Kodu Repository'den Çek
        uses: actions/checkout@v4

      - name: ShellCheck Kurulumu
        run: sudo apt-get install -y shellcheck

      - name: Scriptleri Test Et
        
        run: shellcheck -e SC1091 *.sh