name: Bash Script Kontrolü (CI)

on:
  push:
    branches: [ "main" ] # Eğer ana branch ismin 'master' ise burayı 'master' yap

jobs:
  shellcheck:  
    runs-on: ubuntu-latest # GitHub arka planda sana sanal bir Ubuntu verir

    steps:
      - name: Kodu Repository'den Çek
        uses: actions/checkout@v4

      - name: ShellCheck Kurulumu
        run: sudo apt-get install -y shellcheck

      - name: Scriptleri Test Et
        # Bu adım depodaki tüm .sh uzantılı dosyaları kontrol eder
        run: shellcheck *.sh